import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';

import Player from '../lib/Player';

const INITIAL_DICES = [
  {
    id: 0,
    value: 0,
    checked: false,
  },
  {
    id: 1,
    value: 0,
    checked: false,
  },
  {
    id: 2,
    value: 0,
    checked: false,
  },
  {
    id: 3,
    value: 0,
    checked: false,
  },
  {
    id: 4,
    value: 0,
    checked: false,
  },
];

const Home: NextPage = () => {
  const [coinsP1, setCoinsP1] = useState(30);
  const [coinsP2, setCoinsP2] = useState(30);

  const [p1Dices, setP1Dices] = useState([...INITIAL_DICES]);
  const [p2Dices, setP2Dices] = useState([...INITIAL_DICES]);

  const player1 = new Player('Max');
  const player2 = new Player('Manus');

  /**
   * Kaster terning dersom cheked ikke er true
   */
  const throwDice = (player: number) => {
    if (player === 1) {
      let newArr = p1Dices.map((item) => {
        const value = item.checked
          ? item.value
          : Math.floor(Math.random() * 6 + 1);

        return { ...item, value };
      });
      setP1Dices(newArr);
    }

    if (player === 2) {
      let newArr = p2Dices.map((item) => {
        const value = item.checked
          ? item.value
          : Math.floor(Math.random() * 6 + 1);

        return { ...item, value };
      });
      setP2Dices(newArr);
    }
  };

  /**
   * Markerer en terning som ikke skal kastes på nytt
   */
  const checkDice = (index: number, player: number) => {
    if (player === 1) {
      let newArr = p1Dices.map((item, i) => {
        if (index === i) {
          return { ...item, checked: !p1Dices[index].checked };
        } else {
          return item;
        }
      });
      setP1Dices(newArr);
    }

    if (player === 2) {
      let newArr = p2Dices.map((item, i) => {
        if (index === i) {
          return { ...item, checked: !p2Dices[index].checked };
        } else {
          return item;
        }
      });
      setP2Dices(newArr);
    }
  };

  return (
    <div>
      <Head>
        <title>Dice Poker</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <section>
          <h2>{player1.name}</h2>
          <p>evCoin: {coinsP1}</p>
          {p1Dices.map((dice, index) => (
            <button onClick={() => checkDice(index, 1)} key={dice.id}>
              {dice.value}
            </button>
          ))}
          <button onClick={() => throwDice(1)}>Kast terninger</button>
        </section>
        <section>
          <h2>{player2.name}</h2>
          <p>evCoin: {coinsP2}</p>
          {p2Dices.map((dice, index) => (
            <button onClick={() => checkDice(index, 2)} key={dice.id}>
              {dice.value}
            </button>
          ))}
          <button onClick={() => throwDice(2)}>Kast terninger</button>
        </section>
      </main>
    </div>
  );
};

export default Home;
